# -*- coding: utf-8 -*-
"""atcorder_r.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iqubvPaPdBI2ja9Rp86P3cpE9PTPm-5N
"""

import re

path = 'input.txt'

with open(path) as f:
    print(f.read())

with open(path) as f:
    lines = f.readlines()

print(lines)

lines_strip = [line.strip() for line in lines]
print(lines_strip)



StrA = "".join(lines_strip)
print(StrA)
## StrA is "abc"



pat = r'[0-9]+'                  #抽出するパターン：数字

num_list = re.findall(pat, StrA)  #数字を抽出してリスト化
print (num_list)

l_si_i = [int(s) for s in num_list]
print(l_si_i)

M = l_si_i[-1]
print(M)

l_even = [i for i in l_si_i if M % i == 0]
print(l_even)

#0割でエラー。時間切れ。